config/routes.rb
Rails.application.routes.draw do
  resources :submits, :except => [:edit, :update]

  get 'dashboard', to: 'dashboard#overview'
  get 'dashboard/overview'

  resources :exercises

  devise_for :users, :controllers => {
    :sessions => 'users/sessions',
    :registrations => 'users/registrations'
  }

  root 'welcome#index'

end

app/models/submit.rb
require 'fileutils'
require 'systemu'

class Submit < ActiveRecord::Base
  attr_accessor :file
  include ActiveModel::Validations
  validate :check_file

  validates :exercise_id, presence: true

  belongs_to :user
  belongs_to :exercise

  before_create :store_file
  before_destroy :destroy_file
  after_create :judge_file

  # default scope
  default_scope { order('created_at DESC') }

  private
    def check_file
      if file == nil
        errors.add(:file, "must be not empty")
        return false
      end
      errors.add(:file, "too large file size") if file.size > 1024*1024
      errors.add(:file, "upload file must be '.c' ") if File.extname(file.original_filename) != ".c"
      return false if errors.messages
    end

    # file upload
    def store_file
      dirname = File.dirname(full_path)
      unless File.directory?(dirname)
        FileUtils.mkdir_p(dirname)
      end
      File.open(full_path, "wb") do |f|
        f.write self.content
      end
    end

    def destroy_file
      begin
        # File.unlink full_path

      rescue
        nil
      end
    end

    def full_path
      return Rails.root.join('public/submits/').to_s + self.user.email + "/" + self.exercise.unique_name + ".c"
    end


    def target_path
      return Rails.root.join('public/exercises/').to_s + self.exercise.unique_name
    end

    # judge files
    def judge_file
      dir = File.dirname(full_path)
      t = File.basename(full_path, ".c")
      Dir.chdir(dir) do

        # git の実行
        spawn("git add .")
        spawn("git commit -m \"modified #{t}.c\"")

        # gcc の実行
        looper = "gcc -o exe_#{t} #{t}.c"
        status, stdout, stderr = systemu looper
        if status.exitstatus.to_i != 0
          self.result = "Compile Error"
          self.save
          return false
        end

        # 解答のチェック
        Dir.glob(target_path + "/input/*").each do |input_path|
          output_path = input_path.gsub(/input/, 'output')
          tmp = File.join(dir, "output.txt") 
          puts "Log - #{input_path}"

          # 実際に実行してみる。
          status, stdout, stderr = systemu "./exe_#{t} < #{input_path} > #{tmp}" do |cid|
            begin
              Timeout::timeout(3) do
                # sleep 3
              end
            rescue Timeout::Error
              Process.kill 9, cid
            end
          end

          # diff を取ってエラーかどうかを確認する
          status, stdout, stderr = systemu "diff #{output_path} #{tmp}"
          if status.exitstatus.to_i != 0
            self.result = "Wrong Answer"
            self.save
            return false
          end
          self.result = "Success!"
          self.save
        end

      end
    end
end

app/controllers/submits_controller.rb
class SubmitsController < ApplicationController
  before_action :set_submit, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /submits
  # GET /submits.json
  def index
    @submits = Submit.where(user_id: current_user.id)
  end

  # GET /submits/1
  # GET /submits/1.json
  def show
  end

  # GET /submits/new
  def new
    @submit = Submit.new
  end

  # POST /submits
  # POST /submits.json
  def create
    @submit = Submit.new(submit_params)
    @submit.user = current_user

    # save the file
    upload_file = submit_params[:file]
    if upload_file != nil
      @submit.content = upload_file.read
    end

    # count try count
    @submit.try_count =Submit.where(exercise_id: @submit.exercise_id, user_id: @submit.user_id, ).count + 1

    respond_to do |format|
      if @submit.save
        # Badge 認定
        if @submit.result == "Success!"
          badge = Badge.where(exercise_id: @submit.exercise_id, user_id: @submit.user_id )[0]
          badge.certification = 1
          badge.save
        end

        format.html { redirect_to @submit, notice: 'Submit was successfully created.' }
        format.json { render :show, status: :created, location: @submit }
      else
        format.html { render :new }
        format.json { render json: @submit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submits/1
  # DELETE /submits/1.json
  def destroy
    @submit.destroy
    respond_to do |format|
      format.html { redirect_to submits_url, notice: 'Submit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submit
      @submit = Submit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def submit_params
      params.require(:submit).permit(:user_id, :exercise_id, :result, :try_count, :file)
    end
end

app/helpers/submits_helper.rb
module SubmitsHelper
end

app/views/submits/index.html.erb
<h2 class="sub-header">Submit history</h2>
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>ID</th>
        <th>Exercise</th>
        <th>Result</th>
        <th>Date</th>
        <th>User</th>
        <th>Try count</th>
      </tr>
    </thead>
    <tbody>
      <% @submits.each do |submit| %>
        <tr>
          <td><%= link_to(submit.id, submit)%></td>
          <td><%= link_to submit.exercise.title, submit.exercise %></td>
          <td><% if submit.result == "Success!" %>
            <span class="label label-success">Success!</span>
          <% elsif submit.result == "Wrong Answer" %>
            <span class="label label-warning">Wrong Answer</span>
          <% elsif submit.result == "Compile Error" %>
            <span class="label label-danger">Compile Error</span>
          <% else %>
            <span class="label label-danger">Unknown Error</span>
          <% end %></td>
          <td><%= submit.created_at %></td>
          <td><%= submit.user.email %></td>
          <td><%= submit.try_count %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/submits/new.html.erb
<h2 class="sub-header">New Submit</h2>
<div class="form-responsive">

<%= form_for(@submit) do |f| %>
  <% if @submit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@submit.errors.count, "error") %> prohibited this submit from being saved:</h2>

      <ul>
      <% @submit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :exercise_id %><br>
    <%= f.collection_select :exercise_id, Exercise.all, :id, :title, include_blank: 'Please select submit exercise', autofocus: true, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :file %><br>
    <%= f.file_field :file %>
  </div>
    <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', submits_path %>

</div>

app/views/submits/show.html.erb
<script type="text/javascript">
  
</script>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>ID</th>
        <th>Exercise</th>
        <th>Result</th>
        <th>Date</th>
        <th>User</th>
        <th>Try count</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= link_to(@submit.id, @submit)%></td>
        <td><%= link_to @submit.exercise.title, @submit.exercise %></td>
        <td><% if @submit.result == "Success!" %>
          <span class="label label-success">Success!</span>
        <% elsif @submit.result == "Wrong Answer" %>
          <span class="label label-warning">Wrong Answer</span>
        <% elsif @submit.result == "Compile Error" %>
          <span class="label label-danger">Compile Error</span>
        <% else %>
          <span class="label label-danger">Unknown Error</span>
        <% end %></td>
        <td><%= @submit.created_at %></td>
        <td><%= @submit.user.email %></td>
        <td><%= @submit.try_count %></td>
      </tr>
    </tbody>
  </table>

<p>
  <strong>Code</strong>
  <pre><%= @submit.content %></pre>
</p>

<%= link_to 'Back', submits_path %>