config/routes.rb
Rails.application.routes.draw do
  resources :submits, :except => [:edit, :update]

  get 'dashboard', to: 'dashboard#overview'
  get 'dashboard/overview'

  resources :exercises

  devise_for :users, :controllers => {
    :sessions => 'users/sessions',
    :registrations => 'users/registrations'
  }

  root 'welcome#index'

end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_exercise, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /exercises
  # GET /exercises.json
  def index
    @exercises = Exercise.all
  end

  # GET /exercises/1
  # GET /exercises/1.json
  def show
    @submit = Submit.new
    @submit.exercise = @exercise
  end

  # GET /exercises/new
  def new
    @exercise = Exercise.new
  end

  # GET /exercises/1/edit
  def edit
  end

  # POST /exercises
  # POST /exercises.json
  def create
    @exercise = Exercise.new(exercise_params)

    respond_to do |format|
      if @exercise.save
        format.html { redirect_to @exercise, notice: 'Exercise was successfully created.' }
        format.json { render :show, status: :created, location: @exercise }
      else
        format.html { render :new }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exercises/1
  # PATCH/PUT /exercises/1.json
  def update
    respond_to do |format|
      if @exercise.update(exercise_params)
        format.html { redirect_to @exercise, notice: 'Exercise was successfully updated.' }
        format.json { render :show, status: :ok, location: @exercise }
      else
        format.html { render :edit }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercises/1
  # DELETE /exercises/1.json
  def destroy
    @exercise.destroy
    respond_to do |format|
      format.html { redirect_to exercises_url, notice: 'Exercise was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exercise
      @exercise = Exercise.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exercise_params
      params.require(:exercise).permit(:unique_name, :title, :content_body)
    end
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/views/exercises/_form.html.erb
<%= form_for(@exercise) do |f| %>
  <% if @exercise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exercise.errors.count, "error") %> prohibited this exercise from being saved:</h2>

      <ul>
      <% @exercise.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :unique_name %><br>
    <%= f.text_field :unique_name %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content_body %><br>
    <%= f.text_area :content_body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exercises/edit.html.erb
<h1>Editing exercise</h1>

<%= render 'form' %>

<%= link_to 'Show', @exercise %> |
<%= link_to 'Back', exercises_path %>

app/views/exercises/index.html.erb
<h1>Listing exercises</h1>

<table>
  <thead>
    <tr>
      <th>Unique name</th>
      <th>Title</th>
      <th>Content body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exercises.each do |exercise| %>
      <tr>
        <td><%= exercise.unique_name %></td>
        <td><%= exercise.title %></td>
        <td><%= exercise.content_body %></td>
        <td><%= link_to 'Show', exercise %></td>
        <td><%= link_to 'Edit', edit_exercise_path(exercise) %></td>
        <td><%= link_to 'Destroy', exercise, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exercise', new_exercise_path %>

app/views/exercises/new.html.erb
<h1>New exercise</h1>

<%= render 'form' %>

<%= link_to 'Back', exercises_path %>

app/views/exercises/show.html.erb
<script>
$(function () {
  $('form').submit(function () {
    $(this).find(':submit').attr('disabled', 'disabled');
    $(this).find(':submit').val("Please wait to judge...");
  });
});
</script>
  
<h1 class="page-header"><%= @exercise.title %></h2>
<p>
<% markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML) %>
<%= raw markdown.render(@exercise.content_body) %> 

</p>


<div class="form-responsive">
<h2 class="sub-header">Submit</h2>
<div class="row">
<%= form_for(@submit) do |f| %>
  <% if @submit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@submit.errors.count, "error") %> prohibited this submit from being saved:</h2>

      <ul>
      <% @submit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions col-md-4">
    <%= f.hidden_field :exercise_id %>
    <%= f.file_field :file %>
    <%= f.submit :class => "btn btn-info btn-block", :value => "Submit Answer", :id=> "submitbutton" %>
  </div>
<% end %>
</div>

<%= link_to 'Back', dashboard_path %>

</div>